### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by casey-SK** [freevryheid/nim-gdal#1]
Hey, this is really cool. It would be awesome to have this working with rasters. What is the current status of this project? I've been searching for a way to convert from .jp2 to geotiff within a nim program.

**Comment by freevryheid** [comment]
Yep - essentially dead. These wrappers only address the vector side that I needed at the time to project coords onto routes. I ultimately found a better solution using postgis. No attempt was made to wrap the raster funcs but this should be doable using c2nim.
